### ISSUE TITLE
emails are not being sent if the user had unsubscribed from mautic

### ISSUE THREAD

**Issue by Talbatz** [GoodDollar/GoodServer#123]
### Description
If a person had recieved some email from us via mautic in the past AND had unsubscribed by clicking "unsubscribe" in the email's footer, he would not be able to get magic link emails or any other emails via mautic.

when a user clicks the unsubscribe link, he becomes tagged with "DNC" - do not contact.

### Steps to reproduce
if you want to unsubscribe, click the link in the footer of any email you got thru mautic. 
you are supposed to be seeing a page on our mautic server with a notification of your action. 
visit the same URL again to re-subscribe.
while being unsubscribed you will not get emails sent thru mautic. 

### Supporting data
Future developments planned in mautic are supposed to add multi-vendor support for smtp providers https://forum.mautic.org/t/support-for-multiple-smtp-server/6642 exactly for tackling this issue of transactional vs marketing emails

**Comment by Talbatz** [comment]
Possible solution can be: when goodserver creates or updates a contact on mautic, check if the user exists an if he is DNC, and remove it from DNC if so.
https://developer.mautic.org/#remove-from-do-not-contact

**Comment by StanislavShevchenko** [comment]
Solution Options:
1. Since we have only service emails, when sending an email to the user we will remove the email from the DNC group.
2. Change the logic of "unsubscribe", in the dashboard of the mautic there are options for behavior

![image.png](https://images.zenhubusercontent.com/5d555a8db397280599d9227d/fb0fa3e2-de99-4292-a11f-f2fe8c467029)

@sirpy @Nordwhale @AlexeyKosinski  Please make the decision

**Comment by sirpy** [comment]
when goodserver creates account remove from dnc
