### ISSUE TITLE
(Bug) numbers are parsed as strings on incomming json

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#220]
in /admin/queue incomming numbers are pased as strings and i think also in other endpoints
why?

**Comment by serdiukov-o-nordwhale** [comment]
The issue wasn't in the incorrect request body JSON parsing. All numbers were numbers exactly.
The issue was in the database. @sirpy , you supposed to use Props model to save different props (e.g. database version, claim queue allowed etc). Different props could have different types so you left value with no type specified. That means it was storing 'as is' without exact type casts and we had to cast it value manually on each modification. We wasn't performing it, so, once it was stored as string (from any reason), it becomes a string. And further /admin/queue request (even if allow was exactly an number) performed string concatenation instead of algebraic sum:
![image.png](https://images.zenhubusercontent.com/5e6e2ca830bce88543e4cd2a/8107f713-83f1-49cd-aa15-70524c41b543)

**Comment by serdiukov-o-nordwhale** [comment]
What i've did
- added typecast on database level. There's an option called 'discrimination' - it allows you to describe different schemas for different values of some enum-like string field you could define. E.g. for database version 'value' field  have one type (shape with version: Number), for claim queue options - another one (Number)
- added simple body checker & typecast using express-validator. It allows to check is some field exactly the type we need and cast it to this type explicitly

About other possible cases where numbers could be parsed wrong. I did a quick look over the a) schemas b) express routes

In schemas i found that Mixed type is used in tasks queue (for now - for keep enrollments disposing  only which are strings) and for store hanuka bonuses. In the enrollments processing i managing which i'm saving into DB, and hanuka bonuses also are managing manually (by verificationAPI)

In the routes i haven't found any similar cases where we're receiving some numbers. We have an storageAPI where we receiving large payloads with user, but user schema doesn't have any integers/booleans could be managed via storageAPI.
