### ISSUE TITLE
Server should have cron task to delete FV records

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#288]
To keep users privacy we dont keep a connection between their FV record and their database record
If a user loses his account we have no way to delete his FV record, and so he will never be able to open another account.
After a user passes FV we whitelist him in the identity smart contract. the user will be whitelisted for the "authenticationPeriod" specified in days in the smart contract.
The server should periodically delete FV records of users that did their last FV > authenticationPeriod
- [x] add new database table "faceVerifications" each record: {_id, lastFVDate} (indexed by lastFVDate) (see user-private-provider for defining a mongodb table)
- [x] when user performs FV keep/update a record in "faceVerification" _id=enrollmentIdentifier lastFVDate=now (see verificationAPI.js /verify/face endpoints)
- [x] add cronjob that once a day deletes records that has lastFVDate>authenticationPeriod, issue a call also facetec api to delete the record (see calls to TaskRunner.js registerTask())

**Comment by omerzam** [comment]
authenticationPeriod should be read from the contract
@sirpy which contract do I read this from?

**Comment by serdiukov-o-nordwhale** [comment]
Short pre-amble:
We already have working tasks queue which removes face snapshots. For now:
tasks are added on account removal
cron job collects tasks has been added 24hrs ago (or earlier)
The feature you developed could use that queue as FV snapshots storage. Without adding an separate model and cron job
12:01
To do that we just need to extend a bit queue options:
add the field ( executeAt ) to store the actual date the shanshot should be removed (it could be now or in 24hrs or in 2 weeks)
change condition for select tasks in the cronjob (from createdAt <= <now - 24hrs> to executeAt <= <now>)
add option to cancel tasks (remove them from queue)

Oleksii Serdiukov  12:08 PM
With that option we just need then
after success FV get authentication period value and to add a task for remove shanshot in that time (now + <auth period> days)
but we still need to remove snapshot in 24hrs after account deleted. In that case we need to remove previously created task and re-add it with 24hrs (now + 24h). Also we could set in the env to remove it immediately, in that case you need to set executeAt to <now>
also before FV we’re checking is account was removed last 24hrs (to keep the rule 1 claim / day). For that we’re checking is the dispose tasks exists for enrollment identifier or nor. Since now we’ll always have the task for each identifier, we need to a) add some flag (e.g. isDisposing) to differ 24hr removal from auth period b) set that flag while we queueing the task during account delete c) update condition (add subject.isDisposing: true) when we’re checking disposing state

the one issue, is that the authenticaitonPeriod might change, it can become longer or shorter
okay, we could change executeAt type  from Date to enum ‘auth-period’ | ‘account-removal’. then we don’t need isDisposing flag (will check for executeAt = ‘auth-period’) and should keep createdAt (edited) 
12:30
and in the cron we’ll select (executeAt = 'auth-period' AND createdAt <= <now - auth period value in days>) OR (executeAt = 'account-removal' AND createdAt <= <now - keep enrollments value in hours>)

**Comment by serdiukov-o-nordwhale** [comment]
@sirpy @omerzam 
all that stuff isn't needed (except getAuthenticationPeriod() of course) because actually we already have the tasks queue to dispose enrollments.

How i see the solution:
1. remove `createdAt` from `DelayedTaskSchema`. we will use instead `scheduledAt` Date field with ts when it actually should be executed. We could set any value (now to exec immediately, now + 24h, now + 2 weeks etc)
2. subject field by design could have any value depending of task type. for dispose enrollments it's just a string with enrollmend id now. Need to change it to the object 
```javascript
{ enrollmentIdentifier: string, scheduledAt: Date, isDisposing?: boolean }
```
3. add `cancelTasksQueued` method to the UserPrivateDB with the interface similar to `hasTasksQueued` (but returning `Promise<void>`). It should remove tasks of taskName and filters specified
4. add `taskUtil.js` file, move `DISPOSE_ENROLLMENTS_TASK` constant definition and export function `cancelEnrollmentDisposal(storage, enrollmentIdentifier)` which calls
```javascript
cancelTasksQueued(DISPOSE_ENROLLMENTS_TASK, { 'subject.enrollmentIdentifier': enrollmentIdentifier })
```
this is neet to avoid passing processor to session and to avoid circular imports processor -> session -> processor
5. in `EnrollmentSession` / `onEnrollmentCompleted` add 
```javascript
const authenticationPeriod = await adminApi.getAuthenticationPeriod(); 
const disposeAt = moment().add(authenticationPeriod, 'days').toDate();

await storage.cancelEnrollmentDisposal(enrollmentIdentifier);  // remove existing tasks if any
await storage.enqueueTask(DISPOSE_ENROLLMENTS_TASK, { enrollmentIdentifier, disposeAt })
```
this will add a task to auto remove FV record after authenticationPeriod days passed
6. in `enqueueDisposal` update `enqueueTask`  call to

```javascript
let disposeAt = moment(); 

if (keepEnrollments > 0) { 
  disposeAt = disposeAt.add(keepEnrollments, 'hours'); 
} 

disposeAt = disposeAt.toDate(); 
await storage.cancelEnrollmentDisposal(enrollmentIdentifier); 
await storage.enqueueTask(DISPOSE_ENROLLMENTS_TASK, { enrollmentIdentifier, disposeAt, isDisposing: true })
```

this will add task to be executed ASAP if `keepEnrollments` set to 0 or will add 24h removal. `isDisposing` flag is needed to differ it from authenticationPeriod removal
7. update hasTasksQueued call in isEnqueuedForDisposal to 
```javascript
hasTasksQueued(DISPOSE_ENROLLMENTS_TASK, { subject: { enrollmentIdentifier, isDisposing: true })
```
8. update `disposeEnqueuedEnrollments`. Remove `if (keepEnrollments > 0)...`  condition block. rename enqueuedAtFilters to disposeAtFilters and define it as 
```javascript
const disposeAtFilters = { 'subject.disposeAt': { $lte: moment().toDate() }} 
```
(or just new Date())
this will select all tasks (both on account removal and on authenticationPeriod has passed)

That's all. no need to introduce new mongo model, collection cron task etc. it re-uses everything was before, just
- extends some methods
- adds some utilities
- introduces getAuthenticationPeriod wallet method

**Comment by omerzam** [comment]
- [ ] add to the delayed-task model ```executeAt``` as enum - ‘auth-period’ | ‘account-removal’

- [ ] change subject field from string (current implementation) to object with structure ``` { enrollmentIdentifier: string, scheduledAt: Date, isDisposing?: boolean }```

- [ ] add cancelTasksQueued method to the UserPrivateDB with the interface similar to hasTasksQueued (but returning Promise<void>). It should remove tasks of taskName and filters specified

- [ ] in EnrollmentSession / onEnrollmentCompleted add
```
const authenticationPeriod = await adminApi.getAuthenticationPeriod(); 
const disposeAt = moment().add(authenticationPeriod, 'days').toDate();

await storage.cancelEnrollmentDisposal(enrollmentIdentifier);  // remove existing tasks if any
await storage.enqueueTask(DISPOSE_ENROLLMENTS_TASK, { enrollmentIdentifier, disposeAt })
```
this will add a task to auto remove FV record after authenticationPeriod days passed

- [ ] update disposeEnqueuedEnrollments. Remove if (keepEnrollments > 0)... condition block. rename enqueuedAtFilters to disposeAtFilters and define it as

const disposeAtFilters = { 'subject.disposeAt': { $lte: moment().toDate() }} 

- [ ] in the cron we’ll select (executeAt = 'auth-period' AND createdAt <= <now - auth period value in days>) OR (executeAt = 'account-removal' AND createdAt <= <now - keep enrollments value in hours>)

**Comment by iLystopad** [comment]
The FV record is deleted after a long-unused of account.
The last claim was 26.02.21 and after that, the account hasn't been using for more than 14 days.

Checked on the QA 1.24.1-6
Device: Windows 10 // Google Chrome 89.0.4389.90 

Additional info: Email of the checked account - 1tester8913+obivan@gmail.com

Attachment: https://www.screencast.com/t/nxWNtWySqRe

**Comment by sirpy** [comment]
@iLystopad i'm not sure from the screencast how this was tested. i think this needs to be tested on backend
@serdiukov-o-nordwhale please provide explanation how to test, or perform test together with @iLystopad

**Comment by serdiukov-o-nordwhale** [comment]
@iLystopad for now authentication period is set to half of year, not 14 days. It reads from the blockchain
But we still have 24hrs period after removal. Doesn't matters which case to test (14d or 24h) - it uses the same queue, the same tasks etc

How to test:
- create account, pass verification
- delete account
- re create account (with the same type of login and creds)
- try to verify. you should see 'you fv record is deleting' message and you won't be available to pass FV
- try to verify 24hrs after removal. now you should be able to verify

Also, you could test 'auth period' using mongo client (like Robo3T). I could share connection string via Slack.

How to test:
- create account
- go to Profile -> Privacy, copy your face id. lowercase it 
- on mongo client open gooddollar-dev database, select delayedtasks_stagings collection (for QA) or delatedstasks_fuses (for dev)
- execute `db.getCollection('tasks collection name here').find({ "subject.enrollmentIdentifier": "lower cased face id here" })` query. You should see one record with subject.executeAt = 'auth-period'
- remove your account
- execute the same query. You should see one record with subject.executeAt = 'account-removal'
- wait 24h
- execute the same query. You should see no records found
