### ISSUE TITLE
Migrate heroku logentries to logtail

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#399]
logentries are being depracated
i've added logtail to goodserver-next and it looks good.

need to:
- [x] add logtail to dev and staging
- [x] add similar alerts that we have on logentries to logtail (i think we have for timeout and for  any  Error log , dont forget to notice the error repeat requirements0

**Comment by johnsmith-gooddollar** [comment]
Different servers couldn't use the same "send to email"  intergration and the same slack channel
So:

- for dev/qa I've used option "Notify all the team" instead of email to techadmin@gooddollar.org
- for for dev/qa I've created `goodserver-dev` and `goodserver-qa` private Slack channels
- goodserver-next sends alerts to techadmin@gooddollar.org and to `monitoring-alerts` like it was with LogEntries
